//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP2000.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOP2000Entities : DbContext
    {
        public TOP2000Entities()
            : base("name=TOP2000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artiest> Artiests { get; set; }
        public DbSet<Lijst> Lijsts { get; set; }
        public DbSet<Song> Songs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
